name: npm-publish
on:
  push:
    branches:
      - "*.*.x"

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1.0.0

      - name: Check version changes
        uses: EndBug/version-check@v1.0.0
        id: check

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change! -> ${{ steps.check.outputs.type }}"'

      - name: Set up Node.js for NPM
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v1.2.0
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '10.x'

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Publish package to NPM
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
